version: "2"

linters:
  default: fast
  enable:
    - goimports
    - gofmt
    - misspell
    - gosec
    - unconvert
    - revive
    - gocognit
    - gocyclo
  settings:
    misspell:
      locale: US
    goimports:
      local-prefixes:
        - github.com/erock530/gocloak
    gocognit:
      min-complexity: 15
    gocyclo:
      min-complexity: 15
    gofmt:
      simplify: true
  exclusions:
    paths:
      - (^|/)testdata($|/)
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - dupl
          - gosec
          - gocognit
      - text: "should have a package comment"
