version: "2"

linters:
  default: none
  enable:
    - misspell
    - gosec
    - unconvert
    - revive
    - gocognit
    - gocyclo
  settings:
    misspell:
      locale: US
    gosec:
      excludes:
        - G117
    gocognit:
      min-complexity: 15
    gocyclo:
      min-complexity: 15
  exclusions:
    paths:
      - (^|/)testdata($|/)
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - dupl
          - gosec
          - gocognit
      - text: "should have a package comment"
        linters:
          - revive

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/erock530/gocloak
